name: country_provider2
version: 1.0.2+3
homepage: https://github.com/ericmartineau/country_provider
description: The plugin provides several methods to fetch countries info, Apply
  filter, and perform search operations.
environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
flutter: null
